### ISSUE TITLE
App has stopped when starting

### ISSUE THREAD

**Issue by phuexzy** [HannahMitt/HomeMirror#13]
Help me please, How can I fixed this?  (using android studio 1.2 with emulator of Nexus 7 API 5.0)

Error at AsyncTask

Log:
<code>
09-14 00:29:01.031    3242-3260/com.morristaedt.mirror E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #1
    Process: com.morristaedt.mirror, PID: 3242
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.IllegalStateException: Error handler returned null for wrapped exception.
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:244)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getHourlyForecast(Unknown Source)
            at com.morristaedt.mirror.modules.ForecastModule$1.doInBackground(ForecastModule.java:50)
            at com.morristaedt.mirror.modules.ForecastModule$1.doInBackground(ForecastModule.java:31)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: retrofit.RetrofitError: 403 Forbidden
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at $Proxy0.getHourlyForecast(Unknown Source)
            at com.morristaedt.mirror.modules.ForecastModule$1.doInBackground(ForecastModule.java:50)
            at com.morristaedt.mirror.modules.ForecastModule$1.doInBackground(ForecastModule.java:31)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
</code>

**Comment by phuexzy** [comment]
Sorry, I put wrong API keys. After fixed now it's work.
