### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Rob000** [HannahMitt/HomeMirror#33]
Hi,

after installation, the app crashes on my tablet. Here is the log I can see in Android Studio when I try to open the app. Someone can help me?

Thank you very much.

Rob

11-06 17:41:36.424    7906-7906/com.morristaedt.mirror E/Trace﹕ error opening trace file: No such file or directory (2)
11-06 17:41:36.434    7906-7906/com.morristaedt.mirror W/ActivityThread﹕ Application com.morristaedt.mirror can be debugged on port 8100...
11-06 17:41:36.594    7906-7906/com.morristaedt.mirror D/AndroidRuntime﹕ Shutting down VM
11-06 17:41:36.594    7906-7906/com.morristaedt.mirror W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40cee2a0)
11-06 17:41:36.594    7906-7906/com.morristaedt.mirror E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.morristaedt.mirror/com.morristaedt.mirror.SetUpActivity}: java.lang.IllegalArgumentException: provider==null
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: provider==null
            at android.location.LocationManager.getLastKnownLocation(LocationManager.java:1165)
            at com.morristaedt.mirror.SetUpActivity.setUpLocationMonitoring(SetUpActivity.java:113)
            at com.morristaedt.mirror.SetUpActivity.onCreate(SetUpActivity.java:81)
            at android.app.Activity.performCreate(Activity.java:5008)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1089)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
11-06 17:41:36.674    7906-7908/com.morristaedt.mirror D/dalvikvm﹕ GC_CONCURRENT freed 258K, 6% free 6179K/6535K, paused 2ms+1ms, total 70ms

**Comment by HannahMitt** [comment]
Should be fixed here https://github.com/HannahMitt/HomeMirror/commit/d62d2e2bfb73d9e77cde445c63d01ebd21ae0b70
